### ISSUE TITLE
The retrieved value is: Malformed authorization token

### ISSUE THREAD

**Issue by amarrocco84** [cyberark/conjur-quickstart#14]
Well now I am able to get all the way to the last step which is to fetch the secret but I am getting the following error... "The retrieved value is: Malformed authorization token". What am I doing wrong here?? This was done within the 8 minute limit.

![conjurossmalformed](https://user-images.githubusercontent.com/60936141/74780467-a6b4c880-526d-11ea-98ab-f3fddd781a6a.JPG)

**Comment by sgnn7** [comment]
@amarrocco84 Hmm.... I can see about taking a look at this tomorrow.

**Comment by amarrocco84** [comment]
> @amarrocco84 Hmm.... I can see about taking a look at this tomorrow.

I wasn't using the correct key. Got it working now. Thanks for all the help!

**Comment by izgeri** [comment]
Glad to hear you got it working @amarrocco84! 📈 I'll close this issue now :)
