### ISSUE TITLE
Error in docker pull on mac m1 computer

### ISSUE THREAD

**Issue by sofiadimant** [cyberark/conjur-quickstart#53]
## Summary

When working with mac with m1 chip, and performing "docker-compose pull" command, an error "no matching manifest for linux/arm64/v8 in the manifest list entries" appears

## Steps to Reproduce

Work on macbook m1 chip
1. git clone https://github.com/cyberark/conjur-quickstart.git
2. docker-compose pull

## Expected Results
 No errors appear

## Actual Results

The following error appears: no matching manifest for linux/arm64/v8 in the manifest list entries

## Reproducible

   * [V] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number

latest version 

## Environment setup

macbook with m1 chip

## Additional Information

upon adding: "platform: linux/amd64" to docker-compose.yaml to the services the problem resolved.

**Comment by szh** [comment]
Sounds like this works when adding the necessary metadata. I'm going to close this, please comment and reopen if it's still an issue.
