### ISSUE TITLE
Outdated and EOL PostgreSQL Version

### ISSUE THREAD

**Issue by RokkuCode** [cyberark/conjur-quickstart#57]
In the Docker File the postgreSQL Version 10.16 is stated. If I ignore, that postgreSQL 10 is EOL, this version is also outdated. The last Version of the 10th Branch ist 10.23.

Further I consider this from a security perspective as risk to the security of the application if an outdated postgresql version is used.

**Comment by szh** [comment]
@RokkuCode,
Thank you for reporting this. We'll get this fixed ASAP.

**Comment by szh** [comment]
This has been fixed in 8a68b02. Thank you!
