### ISSUE TITLE
quick-start log format does not match conjur

### ISSUE THREAD

**Issue by sigalsax** [cyberark/conjur-quickstart#8]
The log format in the `conjur quick-start`.

`quick-start` logs:
[ORIGIN] [REQUEST ID] [THREAD ID] [MSG]

Ex:
`[origin=172.29.0.3] [request_id=438d77c9-6c82-42c2-9620-589275dc28cc] [tid=34] Authentication Error: #<Errors::Authentication::InvalidCredentials: CONJ00002E Invalid credentials>`

And from the Conjur repo, the logs look like
`[SEVERITY] [TIMESTAMP] [PROCESS ID] [ORIGIN] [REQUEST ID] [THREAD ID] [MSG]`
Ex:
`INFO 2020/01/05 14:16:00 +0000 [pid=373] [origin=172.24.0.1] [request_id=47dcf956-1481-4256-a972-7b08d3a5b91c] [tid=383] Completed 401 Unauthorized in 68ms`

**Comment by szh** [comment]
I'm going to close this since it's old and likely no longer relevant. Please reopen if it's still a problem.
